# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommandSystemDialog.ui'
#
# Created: Wed Sep 10 00:42:44 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CommandSystemDialog(object):
    def setupUi(self, CommandSystemDialog):
        CommandSystemDialog.setObjectName("CommandSystemDialog")
        CommandSystemDialog.resize(639, 573)
        self.buttonBox = QtGui.QDialogButtonBox(CommandSystemDialog)
        self.buttonBox.setGeometry(QtCore.QRect(500, 30, 91, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(CommandSystemDialog)
        self.label.setGeometry(QtCore.QRect(200, 10, 211, 17))
        self.label.setObjectName("label")
        self.scrollArea = QtGui.QScrollArea(CommandSystemDialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 611, 461))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 800))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 591, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_0 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_0.setGeometry(QtCore.QRect(480, 40, 101, 27))
        self.pushButton_0.setObjectName("pushButton_0")
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 111, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 71, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(360, 20, 61, 17))
        self.label_5.setObjectName("label_5")
        self.SubsysBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_0.setGeometry(QtCore.QRect(30, 40, 201, 31))
        self.SubsysBrowser_0.setObjectName("SubsysBrowser_0")
        self.pktidBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_0.setGeometry(QtCore.QRect(240, 40, 81, 31))
        self.pktidBrowser_0.setObjectName("pktidBrowser_0")
        self.addressBrowser_0 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_0.setGeometry(QtCore.QRect(330, 40, 141, 31))
        self.addressBrowser_0.setObjectName("addressBrowser_0")
        self.SubsysBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_1.setGeometry(QtCore.QRect(30, 80, 201, 31))
        self.SubsysBrowser_1.setObjectName("SubsysBrowser_1")
        self.SubsysBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_2.setGeometry(QtCore.QRect(30, 120, 201, 31))
        self.SubsysBrowser_2.setObjectName("SubsysBrowser_2")
        self.SubsysBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_3.setGeometry(QtCore.QRect(30, 160, 201, 31))
        self.SubsysBrowser_3.setObjectName("SubsysBrowser_3")
        self.SubsysBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_4.setGeometry(QtCore.QRect(30, 200, 201, 31))
        self.SubsysBrowser_4.setObjectName("SubsysBrowser_4")
        self.SubsysBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_5.setGeometry(QtCore.QRect(30, 240, 201, 31))
        self.SubsysBrowser_5.setObjectName("SubsysBrowser_5")
        self.SubsysBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_6.setGeometry(QtCore.QRect(30, 280, 201, 31))
        self.SubsysBrowser_6.setObjectName("SubsysBrowser_6")
        self.SubsysBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_7.setGeometry(QtCore.QRect(30, 320, 201, 31))
        self.SubsysBrowser_7.setObjectName("SubsysBrowser_7")
        self.SubsysBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_8.setGeometry(QtCore.QRect(30, 360, 201, 31))
        self.SubsysBrowser_8.setObjectName("SubsysBrowser_8")
        self.SubsysBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_9.setGeometry(QtCore.QRect(30, 400, 201, 31))
        self.SubsysBrowser_9.setObjectName("SubsysBrowser_9")
        self.SubsysBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_10.setGeometry(QtCore.QRect(30, 440, 201, 31))
        self.SubsysBrowser_10.setObjectName("SubsysBrowser_10")
        self.SubsysBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_11.setGeometry(QtCore.QRect(30, 480, 201, 31))
        self.SubsysBrowser_11.setObjectName("SubsysBrowser_11")
        self.SubsysBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_12.setGeometry(QtCore.QRect(30, 520, 201, 31))
        self.SubsysBrowser_12.setObjectName("SubsysBrowser_12")
        self.SubsysBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_13.setGeometry(QtCore.QRect(30, 560, 201, 31))
        self.SubsysBrowser_13.setObjectName("SubsysBrowser_13")
        self.SubsysBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_14.setGeometry(QtCore.QRect(30, 600, 201, 31))
        self.SubsysBrowser_14.setObjectName("SubsysBrowser_14")
        self.SubsysBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_15.setGeometry(QtCore.QRect(30, 640, 201, 31))
        self.SubsysBrowser_15.setObjectName("SubsysBrowser_15")
        self.SubsysBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_16.setGeometry(QtCore.QRect(30, 680, 201, 31))
        self.SubsysBrowser_16.setObjectName("SubsysBrowser_16")
        self.SubsysBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_17.setGeometry(QtCore.QRect(30, 720, 201, 31))
        self.SubsysBrowser_17.setObjectName("SubsysBrowser_17")
        self.SubsysBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_18.setGeometry(QtCore.QRect(30, 760, 201, 31))
        self.SubsysBrowser_18.setObjectName("SubsysBrowser_18")
        self.SubsysBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_19.setGeometry(QtCore.QRect(30, 800, 201, 31))
        self.SubsysBrowser_19.setObjectName("SubsysBrowser_19")
        self.SubsysBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_20.setGeometry(QtCore.QRect(30, 840, 201, 31))
        self.SubsysBrowser_20.setObjectName("SubsysBrowser_20")
        self.pktidBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_1.setGeometry(QtCore.QRect(240, 80, 81, 31))
        self.pktidBrowser_1.setObjectName("pktidBrowser_1")
        self.pktidBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_2.setGeometry(QtCore.QRect(240, 120, 81, 31))
        self.pktidBrowser_2.setObjectName("pktidBrowser_2")
        self.pktidBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_3.setGeometry(QtCore.QRect(240, 160, 81, 31))
        self.pktidBrowser_3.setObjectName("pktidBrowser_3")
        self.pktidBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_4.setGeometry(QtCore.QRect(240, 200, 81, 31))
        self.pktidBrowser_4.setObjectName("pktidBrowser_4")
        self.pktidBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_5.setGeometry(QtCore.QRect(240, 240, 81, 31))
        self.pktidBrowser_5.setObjectName("pktidBrowser_5")
        self.pktidBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_6.setGeometry(QtCore.QRect(240, 280, 81, 31))
        self.pktidBrowser_6.setObjectName("pktidBrowser_6")
        self.pktidBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_7.setGeometry(QtCore.QRect(240, 320, 81, 31))
        self.pktidBrowser_7.setObjectName("pktidBrowser_7")
        self.pktidBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_8.setGeometry(QtCore.QRect(240, 360, 81, 31))
        self.pktidBrowser_8.setObjectName("pktidBrowser_8")
        self.pktidBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_9.setGeometry(QtCore.QRect(240, 400, 81, 31))
        self.pktidBrowser_9.setObjectName("pktidBrowser_9")
        self.pktidBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_10.setGeometry(QtCore.QRect(240, 440, 81, 31))
        self.pktidBrowser_10.setObjectName("pktidBrowser_10")
        self.pktidBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_11.setGeometry(QtCore.QRect(240, 480, 81, 31))
        self.pktidBrowser_11.setObjectName("pktidBrowser_11")
        self.pktidBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_12.setGeometry(QtCore.QRect(240, 520, 81, 31))
        self.pktidBrowser_12.setObjectName("pktidBrowser_12")
        self.pktidBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_13.setGeometry(QtCore.QRect(240, 560, 81, 31))
        self.pktidBrowser_13.setObjectName("pktidBrowser_13")
        self.pktidBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_14.setGeometry(QtCore.QRect(240, 600, 81, 31))
        self.pktidBrowser_14.setObjectName("pktidBrowser_14")
        self.pktidBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_15.setGeometry(QtCore.QRect(240, 640, 81, 31))
        self.pktidBrowser_15.setObjectName("pktidBrowser_15")
        self.pktidBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_16.setGeometry(QtCore.QRect(240, 680, 81, 31))
        self.pktidBrowser_16.setObjectName("pktidBrowser_16")
        self.pktidBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_17.setGeometry(QtCore.QRect(240, 720, 81, 31))
        self.pktidBrowser_17.setObjectName("pktidBrowser_17")
        self.pktidBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_18.setGeometry(QtCore.QRect(240, 760, 81, 31))
        self.pktidBrowser_18.setObjectName("pktidBrowser_18")
        self.pktidBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_19.setGeometry(QtCore.QRect(240, 800, 81, 31))
        self.pktidBrowser_19.setObjectName("pktidBrowser_19")
        self.pktidBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_20.setGeometry(QtCore.QRect(240, 840, 81, 31))
        self.pktidBrowser_20.setObjectName("pktidBrowser_20")
        self.addressBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_1.setGeometry(QtCore.QRect(330, 80, 141, 31))
        self.addressBrowser_1.setObjectName("addressBrowser_1")
        self.addressBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_2.setGeometry(QtCore.QRect(330, 120, 141, 31))
        self.addressBrowser_2.setObjectName("addressBrowser_2")
        self.addressBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_3.setGeometry(QtCore.QRect(330, 160, 141, 31))
        self.addressBrowser_3.setObjectName("addressBrowser_3")
        self.addressBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_4.setGeometry(QtCore.QRect(330, 200, 141, 31))
        self.addressBrowser_4.setObjectName("addressBrowser_4")
        self.addressBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_5.setGeometry(QtCore.QRect(330, 240, 141, 31))
        self.addressBrowser_5.setObjectName("addressBrowser_5")
        self.addressBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_6.setGeometry(QtCore.QRect(330, 280, 141, 31))
        self.addressBrowser_6.setObjectName("addressBrowser_6")
        self.addressBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_7.setGeometry(QtCore.QRect(330, 320, 141, 31))
        self.addressBrowser_7.setObjectName("addressBrowser_7")
        self.addressBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_8.setGeometry(QtCore.QRect(330, 360, 141, 31))
        self.addressBrowser_8.setObjectName("addressBrowser_8")
        self.addressBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_9.setGeometry(QtCore.QRect(330, 400, 141, 31))
        self.addressBrowser_9.setObjectName("addressBrowser_9")
        self.addressBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_10.setGeometry(QtCore.QRect(330, 440, 141, 31))
        self.addressBrowser_10.setObjectName("addressBrowser_10")
        self.addressBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_11.setGeometry(QtCore.QRect(330, 480, 141, 31))
        self.addressBrowser_11.setObjectName("addressBrowser_11")
        self.addressBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_12.setGeometry(QtCore.QRect(330, 520, 141, 31))
        self.addressBrowser_12.setObjectName("addressBrowser_12")
        self.addressBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_13.setGeometry(QtCore.QRect(330, 560, 141, 31))
        self.addressBrowser_13.setObjectName("addressBrowser_13")
        self.addressBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_14.setGeometry(QtCore.QRect(330, 600, 141, 31))
        self.addressBrowser_14.setObjectName("addressBrowser_14")
        self.addressBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_15.setGeometry(QtCore.QRect(330, 640, 141, 31))
        self.addressBrowser_15.setObjectName("addressBrowser_15")
        self.addressBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_16.setGeometry(QtCore.QRect(330, 680, 141, 31))
        self.addressBrowser_16.setObjectName("addressBrowser_16")
        self.addressBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_17.setGeometry(QtCore.QRect(330, 720, 141, 31))
        self.addressBrowser_17.setObjectName("addressBrowser_17")
        self.addressBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_18.setGeometry(QtCore.QRect(330, 760, 141, 31))
        self.addressBrowser_18.setObjectName("addressBrowser_18")
        self.addressBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_19.setGeometry(QtCore.QRect(330, 800, 141, 31))
        self.addressBrowser_19.setObjectName("addressBrowser_19")
        self.addressBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_20.setGeometry(QtCore.QRect(330, 840, 141, 31))
        self.addressBrowser_20.setObjectName("addressBrowser_20")
        self.pushButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_1.setGeometry(QtCore.QRect(480, 80, 101, 27))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 120, 101, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 160, 101, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 200, 101, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 240, 101, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 280, 101, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 320, 101, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(480, 360, 101, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 400, 101, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setGeometry(QtCore.QRect(480, 440, 101, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setGeometry(QtCore.QRect(480, 480, 101, 27))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_12.setGeometry(QtCore.QRect(480, 520, 101, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_13.setGeometry(QtCore.QRect(480, 560, 101, 27))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_14.setGeometry(QtCore.QRect(480, 600, 101, 27))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_15.setGeometry(QtCore.QRect(480, 640, 101, 27))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_16.setGeometry(QtCore.QRect(480, 680, 101, 27))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_17.setGeometry(QtCore.QRect(480, 720, 101, 27))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_18.setGeometry(QtCore.QRect(480, 760, 101, 27))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_19.setGeometry(QtCore.QRect(480, 800, 101, 27))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_20.setGeometry(QtCore.QRect(480, 840, 101, 27))
        self.pushButton_20.setObjectName("pushButton_20")
        self.SubsysBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.SubsysBrowser_21.setGeometry(QtCore.QRect(30, 880, 201, 31))
        self.SubsysBrowser_21.setObjectName("SubsysBrowser_21")
        self.pktidBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.pktidBrowser_21.setGeometry(QtCore.QRect(240, 880, 81, 31))
        self.pktidBrowser_21.setObjectName("pktidBrowser_21")
        self.addressBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.addressBrowser_21.setGeometry(QtCore.QRect(330, 880, 141, 31))
        self.addressBrowser_21.setObjectName("addressBrowser_21")
        self.pushButton_21 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_21.setGeometry(QtCore.QRect(480, 880, 101, 27))
        self.pushButton_21.setObjectName("pushButton_21")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtGui.QLabel(CommandSystemDialog)
        self.label_2.setGeometry(QtCore.QRect(250, 60, 111, 17))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(CommandSystemDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CommandSystemDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CommandSystemDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CommandSystemDialog)

    def retranslateUi(self, CommandSystemDialog):
        CommandSystemDialog.setWindowTitle(QtGui.QApplication.translate("CommandSystemDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CommandSystemDialog", "cFE/CFS Subsystem Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_0.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CommandSystemDialog", "Subsystem/Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CommandSystemDialog", "Packet ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CommandSystemDialog", "Send To", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_1.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("CommandSystemDialog", "Display Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CommandSystemDialog", "Available Pages", None, QtGui.QApplication.UnicodeUTF8))

