# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenericCommandDialog.ui'
#
# Created: Wed Sep 10 08:43:18 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GenericCommandDialog(object):
    def setupUi(self, GenericCommandDialog):
        GenericCommandDialog.setObjectName("GenericCommandDialog")
        GenericCommandDialog.resize(638, 596)
        self.buttonBox = QtGui.QDialogButtonBox(GenericCommandDialog)
        self.buttonBox.setGeometry(QtCore.QRect(540, 30, 91, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.packetId = QtGui.QLCDNumber(GenericCommandDialog)
        self.packetId.setGeometry(QtCore.QRect(240, 30, 71, 31))
        self.packetId.setObjectName("packetId")
        self.packetIdLabel = QtGui.QLabel(GenericCommandDialog)
        self.packetIdLabel.setGeometry(QtCore.QRect(250, 10, 66, 17))
        self.packetIdLabel.setObjectName("packetIdLabel")
        self.subSystemCommandPageLabel = QtGui.QLabel(GenericCommandDialog)
        self.subSystemCommandPageLabel.setGeometry(QtCore.QRect(70, 10, 81, 17))
        self.subSystemCommandPageLabel.setObjectName("subSystemCommandPageLabel")
        self.subSystemTextBrowser = QtGui.QTextBrowser(GenericCommandDialog)
        self.subSystemTextBrowser.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.subSystemTextBrowser.setObjectName("subSystemTextBrowser")
        self.label = QtGui.QLabel(GenericCommandDialog)
        self.label.setGeometry(QtCore.QRect(270, 80, 81, 17))
        self.label.setObjectName("label")
        self.label_5 = QtGui.QLabel(GenericCommandDialog)
        self.label_5.setGeometry(QtCore.QRect(390, 10, 61, 20))
        self.label_5.setObjectName("label_5")
        self.commandAddressTextBrowser = QtGui.QTextBrowser(GenericCommandDialog)
        self.commandAddressTextBrowser.setGeometry(QtCore.QRect(330, 30, 181, 31))
        self.commandAddressTextBrowser.setObjectName("commandAddressTextBrowser")
        self.scrollArea = QtGui.QScrollArea(GenericCommandDialog)
        self.scrollArea.setGeometry(QtCore.QRect(60, 100, 531, 481))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 511, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.itemLabelTextBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_3.setGeometry(QtCore.QRect(10, 90, 301, 31))
        self.itemLabelTextBrowser_3.setObjectName("itemLabelTextBrowser_3")
        self.itemLabelTextBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_6.setGeometry(QtCore.QRect(10, 210, 301, 31))
        self.itemLabelTextBrowser_6.setObjectName("itemLabelTextBrowser_6")
        self.itemLabelTextBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_5.setGeometry(QtCore.QRect(10, 170, 301, 31))
        self.itemLabelTextBrowser_5.setObjectName("itemLabelTextBrowser_5")
        self.itemLabelTextBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_1.setGeometry(QtCore.QRect(10, 10, 301, 31))
        self.itemLabelTextBrowser_1.setObjectName("itemLabelTextBrowser_1")
        self.itemLabelTextBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_7.setGeometry(QtCore.QRect(10, 250, 301, 31))
        self.itemLabelTextBrowser_7.setObjectName("itemLabelTextBrowser_7")
        self.itemLabelTextBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_2.setGeometry(QtCore.QRect(10, 50, 301, 31))
        self.itemLabelTextBrowser_2.setObjectName("itemLabelTextBrowser_2")
        self.itemLabelTextBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_4.setGeometry(QtCore.QRect(10, 130, 301, 31))
        self.itemLabelTextBrowser_4.setObjectName("itemLabelTextBrowser_4")
        self.itemLabelTextBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_10.setGeometry(QtCore.QRect(10, 370, 301, 31))
        self.itemLabelTextBrowser_10.setObjectName("itemLabelTextBrowser_10")
        self.itemLabelTextBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_14.setGeometry(QtCore.QRect(10, 530, 301, 31))
        self.itemLabelTextBrowser_14.setObjectName("itemLabelTextBrowser_14")
        self.itemLabelTextBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_13.setGeometry(QtCore.QRect(10, 490, 301, 31))
        self.itemLabelTextBrowser_13.setObjectName("itemLabelTextBrowser_13")
        self.itemLabelTextBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_9.setGeometry(QtCore.QRect(10, 330, 301, 31))
        self.itemLabelTextBrowser_9.setObjectName("itemLabelTextBrowser_9")
        self.itemLabelTextBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_12.setGeometry(QtCore.QRect(10, 450, 301, 31))
        self.itemLabelTextBrowser_12.setObjectName("itemLabelTextBrowser_12")
        self.itemLabelTextBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_11.setGeometry(QtCore.QRect(10, 410, 301, 31))
        self.itemLabelTextBrowser_11.setObjectName("itemLabelTextBrowser_11")
        self.itemLabelTextBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_8.setGeometry(QtCore.QRect(10, 290, 301, 31))
        self.itemLabelTextBrowser_8.setObjectName("itemLabelTextBrowser_8")
        self.itemLabelTextBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_15.setGeometry(QtCore.QRect(10, 570, 301, 31))
        self.itemLabelTextBrowser_15.setObjectName("itemLabelTextBrowser_15")
        self.itemLabelTextBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_16.setGeometry(QtCore.QRect(10, 610, 301, 31))
        self.itemLabelTextBrowser_16.setObjectName("itemLabelTextBrowser_16")
        self.itemLabelTextBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_17.setGeometry(QtCore.QRect(10, 650, 301, 31))
        self.itemLabelTextBrowser_17.setObjectName("itemLabelTextBrowser_17")
        self.itemLabelTextBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_18.setGeometry(QtCore.QRect(10, 690, 301, 31))
        self.itemLabelTextBrowser_18.setObjectName("itemLabelTextBrowser_18")
        self.itemLabelTextBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_19.setGeometry(QtCore.QRect(10, 730, 301, 31))
        self.itemLabelTextBrowser_19.setObjectName("itemLabelTextBrowser_19")
        self.itemLabelTextBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_20.setGeometry(QtCore.QRect(10, 770, 301, 31))
        self.itemLabelTextBrowser_20.setObjectName("itemLabelTextBrowser_20")
        self.paramsButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_1.setGeometry(QtCore.QRect(330, 10, 61, 27))
        self.paramsButton_1.setObjectName("paramsButton_1")
        self.paramsButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_2.setGeometry(QtCore.QRect(330, 50, 61, 27))
        self.paramsButton_2.setObjectName("paramsButton_2")
        self.paramsButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_3.setGeometry(QtCore.QRect(330, 90, 61, 27))
        self.paramsButton_3.setObjectName("paramsButton_3")
        self.paramsButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_4.setGeometry(QtCore.QRect(330, 130, 61, 27))
        self.paramsButton_4.setObjectName("paramsButton_4")
        self.paramsButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_5.setGeometry(QtCore.QRect(330, 170, 61, 27))
        self.paramsButton_5.setObjectName("paramsButton_5")
        self.paramsButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_6.setGeometry(QtCore.QRect(330, 210, 61, 27))
        self.paramsButton_6.setObjectName("paramsButton_6")
        self.paramsButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_7.setGeometry(QtCore.QRect(330, 250, 61, 27))
        self.paramsButton_7.setObjectName("paramsButton_7")
        self.paramsButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_8.setGeometry(QtCore.QRect(330, 290, 61, 27))
        self.paramsButton_8.setObjectName("paramsButton_8")
        self.paramsButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_9.setGeometry(QtCore.QRect(330, 330, 61, 27))
        self.paramsButton_9.setObjectName("paramsButton_9")
        self.paramsButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_10.setGeometry(QtCore.QRect(330, 370, 61, 27))
        self.paramsButton_10.setObjectName("paramsButton_10")
        self.paramsButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_11.setGeometry(QtCore.QRect(330, 410, 61, 27))
        self.paramsButton_11.setObjectName("paramsButton_11")
        self.paramsButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_12.setGeometry(QtCore.QRect(330, 450, 61, 27))
        self.paramsButton_12.setObjectName("paramsButton_12")
        self.paramsButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_13.setGeometry(QtCore.QRect(330, 490, 61, 27))
        self.paramsButton_13.setObjectName("paramsButton_13")
        self.paramsButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_14.setGeometry(QtCore.QRect(330, 530, 61, 27))
        self.paramsButton_14.setObjectName("paramsButton_14")
        self.paramsButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_15.setGeometry(QtCore.QRect(330, 570, 61, 27))
        self.paramsButton_15.setObjectName("paramsButton_15")
        self.paramsButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_16.setGeometry(QtCore.QRect(330, 610, 61, 27))
        self.paramsButton_16.setObjectName("paramsButton_16")
        self.paramsButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_17.setGeometry(QtCore.QRect(330, 650, 61, 27))
        self.paramsButton_17.setObjectName("paramsButton_17")
        self.paramsButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_18.setGeometry(QtCore.QRect(330, 690, 61, 27))
        self.paramsButton_18.setObjectName("paramsButton_18")
        self.paramsButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_19.setGeometry(QtCore.QRect(330, 730, 61, 27))
        self.paramsButton_19.setObjectName("paramsButton_19")
        self.paramsButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.paramsButton_20.setGeometry(QtCore.QRect(330, 770, 61, 27))
        self.paramsButton_20.setObjectName("paramsButton_20")
        self.SendButton_1 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_1.setGeometry(QtCore.QRect(420, 10, 71, 27))
        self.SendButton_1.setObjectName("SendButton_1")
        self.SendButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_2.setGeometry(QtCore.QRect(420, 50, 71, 27))
        self.SendButton_2.setObjectName("SendButton_2")
        self.SendButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_3.setGeometry(QtCore.QRect(420, 90, 71, 27))
        self.SendButton_3.setObjectName("SendButton_3")
        self.SendButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_4.setGeometry(QtCore.QRect(420, 130, 71, 27))
        self.SendButton_4.setObjectName("SendButton_4")
        self.SendButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_5.setGeometry(QtCore.QRect(420, 170, 71, 27))
        self.SendButton_5.setObjectName("SendButton_5")
        self.SendButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_6.setGeometry(QtCore.QRect(420, 210, 71, 27))
        self.SendButton_6.setObjectName("SendButton_6")
        self.SendButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_7.setGeometry(QtCore.QRect(420, 250, 71, 27))
        self.SendButton_7.setObjectName("SendButton_7")
        self.SendButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_8.setGeometry(QtCore.QRect(420, 290, 71, 27))
        self.SendButton_8.setObjectName("SendButton_8")
        self.SendButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_9.setGeometry(QtCore.QRect(420, 330, 71, 27))
        self.SendButton_9.setObjectName("SendButton_9")
        self.SendButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_10.setGeometry(QtCore.QRect(420, 370, 71, 27))
        self.SendButton_10.setObjectName("SendButton_10")
        self.SendButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_11.setGeometry(QtCore.QRect(420, 410, 71, 27))
        self.SendButton_11.setObjectName("SendButton_11")
        self.SendButton_12 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_12.setGeometry(QtCore.QRect(420, 450, 71, 27))
        self.SendButton_12.setObjectName("SendButton_12")
        self.SendButton_13 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_13.setGeometry(QtCore.QRect(420, 490, 71, 27))
        self.SendButton_13.setObjectName("SendButton_13")
        self.SendButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_14.setGeometry(QtCore.QRect(420, 530, 71, 27))
        self.SendButton_14.setObjectName("SendButton_14")
        self.SendButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_15.setGeometry(QtCore.QRect(420, 570, 71, 27))
        self.SendButton_15.setObjectName("SendButton_15")
        self.SendButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_16.setGeometry(QtCore.QRect(420, 610, 71, 27))
        self.SendButton_16.setObjectName("SendButton_16")
        self.SendButton_17 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_17.setGeometry(QtCore.QRect(420, 650, 71, 27))
        self.SendButton_17.setObjectName("SendButton_17")
        self.SendButton_18 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_18.setGeometry(QtCore.QRect(420, 690, 71, 27))
        self.SendButton_18.setObjectName("SendButton_18")
        self.SendButton_19 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_19.setGeometry(QtCore.QRect(420, 730, 71, 27))
        self.SendButton_19.setObjectName("SendButton_19")
        self.SendButton_20 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SendButton_20.setGeometry(QtCore.QRect(420, 770, 71, 27))
        self.SendButton_20.setObjectName("SendButton_20")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(GenericCommandDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), GenericCommandDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), GenericCommandDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GenericCommandDialog)

    def retranslateUi(self, GenericCommandDialog):
        GenericCommandDialog.setWindowTitle(QtGui.QApplication.translate("GenericCommandDialog", "Command Page", None, QtGui.QApplication.UnicodeUTF8))
        self.packetIdLabel.setText(QtGui.QApplication.translate("GenericCommandDialog", "Packet ID", None, QtGui.QApplication.UnicodeUTF8))
        self.subSystemCommandPageLabel.setText(QtGui.QApplication.translate("GenericCommandDialog", "Subsystem", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GenericCommandDialog", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send To:", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_1.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_2.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_3.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_4.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_5.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_6.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_7.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_8.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_9.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_10.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_11.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_12.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_13.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_14.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_15.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_16.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_17.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_18.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_19.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.paramsButton_20.setText(QtGui.QApplication.translate("GenericCommandDialog", "Params", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_1.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_2.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_3.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_4.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_5.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_6.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_7.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_8.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_9.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_10.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_11.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_12.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_13.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_14.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_15.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_16.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_17.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_18.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_19.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.SendButton_20.setText(QtGui.QApplication.translate("GenericCommandDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))

