# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenericTelemetryDialog.ui'
#
# Created: Sat Feb 22 07:14:27 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GenericTelemetryDialog(object):
    def setupUi(self, GenericTelemetryDialog):
        GenericTelemetryDialog.setObjectName("GenericTelemetryDialog")
        GenericTelemetryDialog.resize(822, 596)
        self.buttonBox = QtGui.QDialogButtonBox(GenericTelemetryDialog)
        self.buttonBox.setGeometry(QtCore.QRect(680, 20, 91, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.packetId = QtGui.QLCDNumber(GenericTelemetryDialog)
        self.packetId.setGeometry(QtCore.QRect(250, 30, 71, 31))
        self.packetId.setObjectName("packetId")
        self.packetIdLabel = QtGui.QLabel(GenericTelemetryDialog)
        self.packetIdLabel.setGeometry(QtCore.QRect(250, 10, 66, 17))
        self.packetIdLabel.setObjectName("packetIdLabel")
        self.subSystemTelemetryPageLabel = QtGui.QLabel(GenericTelemetryDialog)
        self.subSystemTelemetryPageLabel.setGeometry(QtCore.QRect(30, 10, 191, 17))
        self.subSystemTelemetryPageLabel.setObjectName("subSystemTelemetryPageLabel")
        self.subSystemTextBrowser = QtGui.QTextBrowser(GenericTelemetryDialog)
        self.subSystemTextBrowser.setGeometry(QtCore.QRect(50, 30, 141, 31))
        self.subSystemTextBrowser.setObjectName("subSystemTextBrowser")
        self.label = QtGui.QLabel(GenericTelemetryDialog)
        self.label.setGeometry(QtCore.QRect(40, 80, 151, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(GenericTelemetryDialog)
        self.label_2.setGeometry(QtCore.QRect(210, 80, 151, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(GenericTelemetryDialog)
        self.label_3.setGeometry(QtCore.QRect(620, 80, 151, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(GenericTelemetryDialog)
        self.label_4.setGeometry(QtCore.QRect(450, 80, 151, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(GenericTelemetryDialog)
        self.label_5.setGeometry(QtCore.QRect(450, 10, 111, 20))
        self.label_5.setObjectName("label_5")
        self.sequenceCount = QtGui.QTextBrowser(GenericTelemetryDialog)
        self.sequenceCount.setGeometry(QtCore.QRect(450, 30, 101, 31))
        self.sequenceCount.setObjectName("sequenceCount")
        self.scrollArea = QtGui.QScrollArea(GenericTelemetryDialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 791, 481))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -437, 771, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.itemValueTextBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_7.setGeometry(QtCore.QRect(190, 250, 151, 31))
        self.itemValueTextBrowser_7.setObjectName("itemValueTextBrowser_7")
        self.itemLabelTextBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_3.setGeometry(QtCore.QRect(10, 90, 161, 31))
        self.itemLabelTextBrowser_3.setObjectName("itemLabelTextBrowser_3")
        self.itemLabelTextBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_6.setGeometry(QtCore.QRect(10, 210, 161, 31))
        self.itemLabelTextBrowser_6.setObjectName("itemLabelTextBrowser_6")
        self.itemLabelTextBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_5.setGeometry(QtCore.QRect(10, 170, 161, 31))
        self.itemLabelTextBrowser_5.setObjectName("itemLabelTextBrowser_5")
        self.itemLabelTextBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_1.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.itemLabelTextBrowser_1.setObjectName("itemLabelTextBrowser_1")
        self.itemValueTextBrowser_1 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_1.setGeometry(QtCore.QRect(190, 10, 151, 31))
        self.itemValueTextBrowser_1.setObjectName("itemValueTextBrowser_1")
        self.itemLabelTextBrowser_7 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_7.setGeometry(QtCore.QRect(10, 250, 161, 31))
        self.itemLabelTextBrowser_7.setObjectName("itemLabelTextBrowser_7")
        self.itemValueTextBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_4.setGeometry(QtCore.QRect(190, 130, 151, 31))
        self.itemValueTextBrowser_4.setObjectName("itemValueTextBrowser_4")
        self.itemLabelTextBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_2.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.itemLabelTextBrowser_2.setObjectName("itemLabelTextBrowser_2")
        self.itemValueTextBrowser_6 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_6.setGeometry(QtCore.QRect(190, 210, 151, 31))
        self.itemValueTextBrowser_6.setObjectName("itemValueTextBrowser_6")
        self.itemValueTextBrowser_2 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_2.setGeometry(QtCore.QRect(190, 50, 151, 31))
        self.itemValueTextBrowser_2.setObjectName("itemValueTextBrowser_2")
        self.itemValueTextBrowser_5 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_5.setGeometry(QtCore.QRect(190, 170, 151, 31))
        self.itemValueTextBrowser_5.setObjectName("itemValueTextBrowser_5")
        self.itemValueTextBrowser_3 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_3.setGeometry(QtCore.QRect(190, 90, 151, 31))
        self.itemValueTextBrowser_3.setObjectName("itemValueTextBrowser_3")
        self.itemLabelTextBrowser_4 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_4.setGeometry(QtCore.QRect(10, 130, 161, 31))
        self.itemLabelTextBrowser_4.setObjectName("itemLabelTextBrowser_4")
        self.itemValueTextBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_14.setGeometry(QtCore.QRect(190, 530, 151, 31))
        self.itemValueTextBrowser_14.setObjectName("itemValueTextBrowser_14")
        self.itemLabelTextBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_10.setGeometry(QtCore.QRect(10, 370, 161, 31))
        self.itemLabelTextBrowser_10.setObjectName("itemLabelTextBrowser_10")
        self.itemLabelTextBrowser_14 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_14.setGeometry(QtCore.QRect(10, 530, 161, 31))
        self.itemLabelTextBrowser_14.setObjectName("itemLabelTextBrowser_14")
        self.itemLabelTextBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_13.setGeometry(QtCore.QRect(10, 490, 161, 31))
        self.itemLabelTextBrowser_13.setObjectName("itemLabelTextBrowser_13")
        self.itemLabelTextBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_9.setGeometry(QtCore.QRect(10, 330, 161, 31))
        self.itemLabelTextBrowser_9.setObjectName("itemLabelTextBrowser_9")
        self.itemValueTextBrowser_9 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_9.setGeometry(QtCore.QRect(190, 330, 151, 31))
        self.itemValueTextBrowser_9.setObjectName("itemValueTextBrowser_9")
        self.itemLabelTextBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_12.setGeometry(QtCore.QRect(10, 450, 161, 31))
        self.itemLabelTextBrowser_12.setObjectName("itemLabelTextBrowser_12")
        self.itemLabelTextBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_11.setGeometry(QtCore.QRect(10, 410, 161, 31))
        self.itemLabelTextBrowser_11.setObjectName("itemLabelTextBrowser_11")
        self.itemValueTextBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_8.setGeometry(QtCore.QRect(190, 290, 151, 31))
        self.itemValueTextBrowser_8.setObjectName("itemValueTextBrowser_8")
        self.itemValueTextBrowser_11 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_11.setGeometry(QtCore.QRect(190, 410, 151, 31))
        self.itemValueTextBrowser_11.setObjectName("itemValueTextBrowser_11")
        self.itemValueTextBrowser_12 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_12.setGeometry(QtCore.QRect(190, 450, 151, 31))
        self.itemValueTextBrowser_12.setObjectName("itemValueTextBrowser_12")
        self.itemValueTextBrowser_10 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_10.setGeometry(QtCore.QRect(190, 370, 151, 31))
        self.itemValueTextBrowser_10.setObjectName("itemValueTextBrowser_10")
        self.itemValueTextBrowser_13 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_13.setGeometry(QtCore.QRect(190, 490, 151, 31))
        self.itemValueTextBrowser_13.setObjectName("itemValueTextBrowser_13")
        self.itemLabelTextBrowser_8 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_8.setGeometry(QtCore.QRect(10, 290, 161, 31))
        self.itemLabelTextBrowser_8.setObjectName("itemLabelTextBrowser_8")
        self.itemLabelTextBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_15.setGeometry(QtCore.QRect(10, 570, 161, 31))
        self.itemLabelTextBrowser_15.setObjectName("itemLabelTextBrowser_15")
        self.itemLabelTextBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_16.setGeometry(QtCore.QRect(10, 610, 161, 31))
        self.itemLabelTextBrowser_16.setObjectName("itemLabelTextBrowser_16")
        self.itemLabelTextBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_17.setGeometry(QtCore.QRect(10, 650, 161, 31))
        self.itemLabelTextBrowser_17.setObjectName("itemLabelTextBrowser_17")
        self.itemLabelTextBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_18.setGeometry(QtCore.QRect(10, 690, 161, 31))
        self.itemLabelTextBrowser_18.setObjectName("itemLabelTextBrowser_18")
        self.itemLabelTextBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_19.setGeometry(QtCore.QRect(10, 730, 161, 31))
        self.itemLabelTextBrowser_19.setObjectName("itemLabelTextBrowser_19")
        self.itemLabelTextBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_20.setGeometry(QtCore.QRect(10, 770, 161, 31))
        self.itemLabelTextBrowser_20.setObjectName("itemLabelTextBrowser_20")
        self.itemValueTextBrowser_15 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_15.setGeometry(QtCore.QRect(190, 570, 151, 31))
        self.itemValueTextBrowser_15.setObjectName("itemValueTextBrowser_15")
        self.itemValueTextBrowser_16 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_16.setGeometry(QtCore.QRect(190, 610, 151, 31))
        self.itemValueTextBrowser_16.setObjectName("itemValueTextBrowser_16")
        self.itemValueTextBrowser_17 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_17.setGeometry(QtCore.QRect(190, 650, 151, 31))
        self.itemValueTextBrowser_17.setObjectName("itemValueTextBrowser_17")
        self.itemValueTextBrowser_18 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_18.setGeometry(QtCore.QRect(190, 690, 151, 31))
        self.itemValueTextBrowser_18.setObjectName("itemValueTextBrowser_18")
        self.itemValueTextBrowser_19 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_19.setGeometry(QtCore.QRect(190, 730, 151, 31))
        self.itemValueTextBrowser_19.setObjectName("itemValueTextBrowser_19")
        self.itemValueTextBrowser_20 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_20.setGeometry(QtCore.QRect(190, 770, 151, 31))
        self.itemValueTextBrowser_20.setObjectName("itemValueTextBrowser_20")
        self.itemLabelTextBrowser_36 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_36.setGeometry(QtCore.QRect(420, 610, 161, 31))
        self.itemLabelTextBrowser_36.setObjectName("itemLabelTextBrowser_36")
        self.itemLabelTextBrowser_28 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_28.setGeometry(QtCore.QRect(420, 290, 161, 31))
        self.itemLabelTextBrowser_28.setObjectName("itemLabelTextBrowser_28")
        self.itemLabelTextBrowser_39 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_39.setGeometry(QtCore.QRect(420, 730, 161, 31))
        self.itemLabelTextBrowser_39.setObjectName("itemLabelTextBrowser_39")
        self.itemLabelTextBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_21.setGeometry(QtCore.QRect(420, 10, 161, 31))
        self.itemLabelTextBrowser_21.setObjectName("itemLabelTextBrowser_21")
        self.itemLabelTextBrowser_29 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_29.setGeometry(QtCore.QRect(420, 330, 161, 31))
        self.itemLabelTextBrowser_29.setObjectName("itemLabelTextBrowser_29")
        self.itemLabelTextBrowser_30 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_30.setGeometry(QtCore.QRect(420, 370, 161, 31))
        self.itemLabelTextBrowser_30.setObjectName("itemLabelTextBrowser_30")
        self.itemLabelTextBrowser_22 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_22.setGeometry(QtCore.QRect(420, 50, 161, 31))
        self.itemLabelTextBrowser_22.setObjectName("itemLabelTextBrowser_22")
        self.itemLabelTextBrowser_38 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_38.setGeometry(QtCore.QRect(420, 690, 161, 31))
        self.itemLabelTextBrowser_38.setObjectName("itemLabelTextBrowser_38")
        self.itemLabelTextBrowser_35 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_35.setGeometry(QtCore.QRect(420, 570, 161, 31))
        self.itemLabelTextBrowser_35.setObjectName("itemLabelTextBrowser_35")
        self.itemLabelTextBrowser_34 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_34.setGeometry(QtCore.QRect(420, 530, 161, 31))
        self.itemLabelTextBrowser_34.setObjectName("itemLabelTextBrowser_34")
        self.itemLabelTextBrowser_37 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_37.setGeometry(QtCore.QRect(420, 650, 161, 31))
        self.itemLabelTextBrowser_37.setObjectName("itemLabelTextBrowser_37")
        self.itemLabelTextBrowser_27 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_27.setGeometry(QtCore.QRect(420, 250, 161, 31))
        self.itemLabelTextBrowser_27.setObjectName("itemLabelTextBrowser_27")
        self.itemLabelTextBrowser_23 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_23.setGeometry(QtCore.QRect(420, 90, 161, 31))
        self.itemLabelTextBrowser_23.setObjectName("itemLabelTextBrowser_23")
        self.itemLabelTextBrowser_40 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_40.setGeometry(QtCore.QRect(420, 770, 161, 31))
        self.itemLabelTextBrowser_40.setObjectName("itemLabelTextBrowser_40")
        self.itemLabelTextBrowser_25 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_25.setGeometry(QtCore.QRect(420, 170, 161, 31))
        self.itemLabelTextBrowser_25.setObjectName("itemLabelTextBrowser_25")
        self.itemLabelTextBrowser_26 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_26.setGeometry(QtCore.QRect(420, 210, 161, 31))
        self.itemLabelTextBrowser_26.setObjectName("itemLabelTextBrowser_26")
        self.itemLabelTextBrowser_31 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_31.setGeometry(QtCore.QRect(420, 410, 161, 31))
        self.itemLabelTextBrowser_31.setObjectName("itemLabelTextBrowser_31")
        self.itemLabelTextBrowser_33 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_33.setGeometry(QtCore.QRect(420, 490, 161, 31))
        self.itemLabelTextBrowser_33.setObjectName("itemLabelTextBrowser_33")
        self.itemLabelTextBrowser_24 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_24.setGeometry(QtCore.QRect(420, 130, 161, 31))
        self.itemLabelTextBrowser_24.setObjectName("itemLabelTextBrowser_24")
        self.itemLabelTextBrowser_32 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemLabelTextBrowser_32.setGeometry(QtCore.QRect(420, 450, 161, 31))
        self.itemLabelTextBrowser_32.setObjectName("itemLabelTextBrowser_32")
        self.itemValueTextBrowser_40 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_40.setGeometry(QtCore.QRect(600, 770, 151, 31))
        self.itemValueTextBrowser_40.setObjectName("itemValueTextBrowser_40")
        self.itemValueTextBrowser_33 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_33.setGeometry(QtCore.QRect(600, 490, 151, 31))
        self.itemValueTextBrowser_33.setObjectName("itemValueTextBrowser_33")
        self.itemValueTextBrowser_29 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_29.setGeometry(QtCore.QRect(600, 330, 151, 31))
        self.itemValueTextBrowser_29.setObjectName("itemValueTextBrowser_29")
        self.itemValueTextBrowser_22 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_22.setGeometry(QtCore.QRect(600, 50, 151, 31))
        self.itemValueTextBrowser_22.setObjectName("itemValueTextBrowser_22")
        self.itemValueTextBrowser_36 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_36.setGeometry(QtCore.QRect(600, 610, 151, 31))
        self.itemValueTextBrowser_36.setObjectName("itemValueTextBrowser_36")
        self.itemValueTextBrowser_23 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_23.setGeometry(QtCore.QRect(600, 90, 151, 31))
        self.itemValueTextBrowser_23.setObjectName("itemValueTextBrowser_23")
        self.itemValueTextBrowser_27 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_27.setGeometry(QtCore.QRect(600, 250, 151, 31))
        self.itemValueTextBrowser_27.setObjectName("itemValueTextBrowser_27")
        self.itemValueTextBrowser_31 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_31.setGeometry(QtCore.QRect(600, 410, 151, 31))
        self.itemValueTextBrowser_31.setObjectName("itemValueTextBrowser_31")
        self.itemValueTextBrowser_30 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_30.setGeometry(QtCore.QRect(600, 370, 151, 31))
        self.itemValueTextBrowser_30.setObjectName("itemValueTextBrowser_30")
        self.itemValueTextBrowser_39 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_39.setGeometry(QtCore.QRect(600, 730, 151, 31))
        self.itemValueTextBrowser_39.setObjectName("itemValueTextBrowser_39")
        self.itemValueTextBrowser_21 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_21.setGeometry(QtCore.QRect(600, 10, 151, 31))
        self.itemValueTextBrowser_21.setObjectName("itemValueTextBrowser_21")
        self.itemValueTextBrowser_24 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_24.setGeometry(QtCore.QRect(600, 130, 151, 31))
        self.itemValueTextBrowser_24.setObjectName("itemValueTextBrowser_24")
        self.itemValueTextBrowser_26 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_26.setGeometry(QtCore.QRect(600, 210, 151, 31))
        self.itemValueTextBrowser_26.setObjectName("itemValueTextBrowser_26")
        self.itemValueTextBrowser_32 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_32.setGeometry(QtCore.QRect(600, 450, 151, 31))
        self.itemValueTextBrowser_32.setObjectName("itemValueTextBrowser_32")
        self.itemValueTextBrowser_34 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_34.setGeometry(QtCore.QRect(600, 530, 151, 31))
        self.itemValueTextBrowser_34.setObjectName("itemValueTextBrowser_34")
        self.itemValueTextBrowser_38 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_38.setGeometry(QtCore.QRect(600, 690, 151, 31))
        self.itemValueTextBrowser_38.setObjectName("itemValueTextBrowser_38")
        self.itemValueTextBrowser_28 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_28.setGeometry(QtCore.QRect(600, 290, 151, 31))
        self.itemValueTextBrowser_28.setObjectName("itemValueTextBrowser_28")
        self.itemValueTextBrowser_25 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_25.setGeometry(QtCore.QRect(600, 170, 151, 31))
        self.itemValueTextBrowser_25.setObjectName("itemValueTextBrowser_25")
        self.itemValueTextBrowser_37 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_37.setGeometry(QtCore.QRect(600, 650, 151, 31))
        self.itemValueTextBrowser_37.setObjectName("itemValueTextBrowser_37")
        self.itemValueTextBrowser_35 = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.itemValueTextBrowser_35.setGeometry(QtCore.QRect(600, 570, 151, 31))
        self.itemValueTextBrowser_35.setObjectName("itemValueTextBrowser_35")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(GenericTelemetryDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), GenericTelemetryDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), GenericTelemetryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GenericTelemetryDialog)

    def retranslateUi(self, GenericTelemetryDialog):
        GenericTelemetryDialog.setWindowTitle(QtGui.QApplication.translate("GenericTelemetryDialog", "Telemetry Page", None, QtGui.QApplication.UnicodeUTF8))
        self.packetIdLabel.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Packet ID", None, QtGui.QApplication.UnicodeUTF8))
        self.subSystemTelemetryPageLabel.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Subsystem Telemetry Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Telemetry Point Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Telemetry Point Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Telemetry Point Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Telemetry Point Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GenericTelemetryDialog", "Sequence Count", None, QtGui.QApplication.UnicodeUTF8))

